name: GPG Signed Commit

on:
  workflow_dispatch:
    # This allows the workflow to be triggered manually

jobs:
  create-signed-commit:
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # This ensures we get commit history
          fetch-depth: 0

      # - name: Configure Git
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     # Enable commit signature verification using GitHub token
      #     git config --global commit.gpgsign true

      - name: Create random file
        run: |
          # Generate a random filename
          FILENAME="random-file-$(date +%s).txt"

          # Create file with random content
          echo "This is a randomly generated file created at $(date)" > $FILENAME
          echo "Random number: $RANDOM" >> $FILENAME

          # Use special committer identity for GitHub Actions
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add $FILENAME
          git commit -m "Add randomly generated file via GitHub Actions"
          git push origin HEAD

          echo "Created and committed file: $FILENAME"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
