name: GPG Signed Commit

on:
  workflow_dispatch:
    # This allows the workflow to be triggered manually

jobs:
  create-signed-commit:
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # This is important if you have branch protection rules!
      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.PINAX_BOT_PGP_PRIVATE_KEY }}
          passphrase: ${{ secrets.PINAX_BOT_PGP_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create random file
        run: |
          FILENAME="random-file-$(date +%s).txt"
          echo "This is a randomly generated file created at $(date)" > $FILENAME
          echo "Random number: $RANDOM" >> $FILENAME


      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Add file from GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PINAX_BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}

      # - name: Import GPG key and setup git
      #   run: |
      #     echo "$GPG_PRIVATE_KEY" | gpg --batch --import
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global commit.gpgsign true
      #     git config --global user.signingkey 336CEE352C31CE1042D7D8B8ABA2CFF52B057F30
      #     git config --global gpg.program gpg
      #   env:
      #     GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      # - name: Commit and push changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Add file from GitHub Actions
