name: GPG Signed Commit

on:
  workflow_dispatch:
    # This allows the workflow to be triggered manually

jobs:
  create-signed-commit:
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create random file
        run: |
          # Generate a random filename
          FILENAME="random-file-$(date +%s).txt"

          # Create file with random content
          echo "This is a randomly generated file created at $(date)" > $FILENAME
          echo "Random number: $RANDOM" >> $FILENAME

      - name: Push with signed commit
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          # author_name: "github-actions[bot]"
          message: "Add signed commit from GitHub Actions"
