name: GPG Signed Commit

on:
  workflow_dispatch:
    # This allows the workflow to be triggered manually

jobs:
  create-signed-commit:
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create random file
        run: |
          FILENAME="random-file-$(date +%s).txt"
          echo "This is a randomly generated file created at $(date)" > $FILENAME
          echo "Random number: $RANDOM" >> $FILENAME

      - name: Import GPG key and setup git
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global commit.gpgsign true
          git config --global user.signingkey 8FBE20CB917E1472B37F8B99EC86BB0B9753F31A
          git config --global gpg.program gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add file from GitHub Actions
